sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script:
    - git clone https://github.com/luizdepra/hugo-coder.git themes/coder
    - hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $BlogTravisCI
    on:
        branch: code
    local_dir: public
    repo: xuren87/xuren87.github.io
    fqdn: xratom.com
    target_branch: master
    email: nichokiki@hotmail.com
    name: xuren87